{% set name = "qtwirl" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 974b9be71a0d6990bc8c9d8eab30135c67235a7bc8018434d95ef8adfb31f25a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - root
    - alphatwirl >=0.23.3

test:
  imports:
    - qtwirl

about:
  home: https://github.com/alphatwirl/qtwirl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'qtwirl (quick-twirl), a one-function interface to AlphaTwirl'
  description: |
    qtwirl (quick-twirl) provides one-function interface to AlphaTwirl.
  dev_url: https://github.com/alphatwirl/qtwirl
  doc_url: https://github.com/alphatwirl/qtwirl#qtwirl

extra:
  recipe-maintainers:
    - TaiSakuma
