travis:
  secure:
    BINSTAR_TOKEN: AuJfMcGwEpO8zOL0ZR9077B9CHovO89gRQ8LIRHCI5ldiuyFq6HLjAoXYNTAtWzosyzNGjNdl2rROeyi/ik/Ps27dELl8nluUIC3j/CVHDxNGywILUg3DOVTPCycBM/KOSsqfTXwhfPdJJ0Cu96opNzbyPnol1IMyvu2qYR0mjlBi+5vuK9KKB0z94RtouLapa1zs3UtQDZ6K05e7kiETfx0r7w1vD48TySn0kz+516jvWtXR4FznBf8GP/5w5yD2C1i6pxmY+PnTPROBjDBnKIU1UKzm9fo628wAEzm0d9umeAHdbJgJksOu0nfMhJuX9v++6NzpJv5WfL3Uv7wtevTM2zkXJ71KCAt9UXNUngI87NynmkBaVIXTsv6NTh7CRZlY5vregim29taseGVigACKvkXZcWpvekaM7aWiLxPV2iwjfQudJybj4lkHf5KZJvoCelrfnp1dsC/QwQgXHfhM5GEmlJoDCqym4fPEq3NXi19KGQ7ZomVYxEGkHa5vKT2DZWfe/YF7Kh13xCCMEEo8xy1Uiilj5RB8JJAAvoPzEekmxz7r6Say5oOcUHI5t1CKcmJWxqfRKwrV2HbNdDoNBUmTbWkuWgXmKEBP/BbgUGnfwMELd96jQR+QsoBsr/bczG2jRaVixUvlsydcau4oX7Q4ehxwubgrf7Snqc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
